name: .NET

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install WASM
      run: dotnet workload install wasm-tools 
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test -c Release --collect:"XPlat Code Coverage" --results-directory ./coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install WASM
      run: dotnet workload install wasm-tools 
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -o 'drop'
    # - name: Variable Substitution
    #   uses: microsoft/variable-substitution@v1
    #   with:
    #     files: '**/drop/appsettings.Production.json'
    #   env:
    #     ConnectionStrings.DefaultConnection: ${{ secrets.connectionstring }}
